# Generated by Django 5.2.5 on 2025-08-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_images/default_avatar.png', upload_to='avatars/'),
        ),
    ]
